--
-- Script was generated by Devart dbForge Studio for MySQL, Version 7.2.78.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 18/03/2018 11:57:39 a.m.
-- Server version: 5.5.5-10.1.30-MariaDB
-- Client version: 4.1
--


-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set default database
--
USE galeria;

--
-- Definition for table fotos
--
DROP TABLE IF EXISTS fotos;
CREATE TABLE fotos (
  id INT(11) NOT NULL AUTO_INCREMENT,
  titulo VARCHAR(200) BINARY NOT NULL,
  imagen VARCHAR(200) BINARY NOT NULL,
  texto TEXT BINARY NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 11
AVG_ROW_LENGTH = 2048
CHARACTER SET utf8
COLLATE utf8_bin;

-- 
-- Dumping data for table fotos
--
INSERT INTO fotos VALUES
(1, '', 'Chrysanthemum.jpg', ''),
(2, '', 'Desert.jpg', ''),
(3, '', 'Hydrangeas.jpg', ''),
(4, '', 'Jellyfish.jpg', ''),
(5, '', 'Koala.jpg', ''),
(6, '', 'Lighthouse.jpg', ''),
(7, '', 'Lighthouse.jpg', ''),
(8, '', 'Penguins.jpg', ''),
(9, '', 'Tulips.jpg', ''),
(10, '', 'BACKGROUNDDEFAULT.jpg', '');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;